# Docker Compose configuration for Maestro separated deployment
# This deploys API and UI as separate containers
#
# Usage:
#   docker compose -f compose.separated.yml up -d
#   docker compose -f compose.separated.yml down

include:
  - compose.base.yml

services:
  maestro-api:
    image: io.maestro/api:latest
    container_name: maestro-api
    environment:
      # Database Configuration
      DB_USERNAME: maestro
      DB_PASSWORD: maestro
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/maestro

      # Application Configuration
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_LOG_LEVEL: INFO

      # CORS Configuration - Allow UI to access API
      QUARKUS_HTTP_CORS: "true"
      QUARKUS_HTTP_CORS_ORIGINS: http://localhost:3000,http://maestro-ui:3000
      QUARKUS_HTTP_CORS_METHODS: GET,POST,PUT,DELETE,OPTIONS
      QUARKUS_HTTP_CORS_HEADERS: Content-Type,Authorization,Accept
      QUARKUS_HTTP_CORS_EXPOSED_HEADERS: Location

      # Liquibase Configuration
      QUARKUS_LIQUIBASE_MIGRATE_AT_START: "true"
      QUARKUS_LIQUIBASE_CLEAN_AT_START: "false"
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - maestro-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/q/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  maestro-ui:
    image: io.maestro/ui:latest
    container_name: maestro-ui
    environment:
      # API Backend URL - configured at runtime via /config.js
      # This should be the URL accessible from the browser (external URL)
      MAESTRO_UI_API_URL: http://localhost:8081

      # HTTP Port Configuration
      QUARKUS_HTTP_PORT: 8080
    ports:
      - "3000:8080"
    depends_on:
      maestro-api:
        condition: service_healthy
    networks:
      - maestro-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
